# Generated by Django 3.1.5 on 2021-01-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_Forest', '0003_auto_20210120_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
