# Generated by Django 3.1.5 on 2021-01-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_Forest', '0004_auto_20210120_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
