# Generated by Django 3.1.5 on 2021-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_Forest', '0007_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
